hw_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('quotes.urls')),
    path('users/', include('users.urls')),
    path('admin/', admin.site.urls)
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quotes/urls.py
from django.urls import path

from . import views

app_name = 'quotes'

urlpatterns = [
    path('', views.main, name='root'),
    path('<int:page>', views.main, name='root_paginate'),
    path('add-quote/', views.add_quote, name='add_quote'),
    path('add-author/', views.add_author, name='add_author'),
    path('author/<str:_id>/', views.author_info, name='author_info'),
    path('tag/<str:tag_name>', views.quotes_by_tag, name='quotes_by_tag')
]

users/urls.py
from django.urls import path, include

from django.contrib.auth.views import LoginView, LogoutView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView

from . import views
from .forms import LoginForm, RegisterForm

app_name = 'users'

urlpatterns = [
    path('signup/', views.RegisterView.as_view(), name='signup'),
    path('signin/', LoginView.as_view(template_name='users/login.html', form_class=LoginForm), name='signin'),
    path('logout/', views.logoutuser, name='logoutuser'),
    path('profile/', views.profile, name='profile'),
    path('reset-password/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

quotes/models.py
from mongoengine import Document, StringField, DateTimeField, ListField, ReferenceField

class Author(Document):
    fullname = StringField(max_length=50)
    born_date = StringField(max_length=50)
    born_location = StringField(max_length=150)
    description = StringField()
    created_at = DateTimeField(required=True)

    def __str__(self):
        return self.fullname

class Tag(Document):
    name = StringField(max_length=60, unique=True)

    def __str__(self):
        return self.name

class Quote(Document):
    quote = StringField()
    tags = ListField(ReferenceField(Tag))
    author = ReferenceField(Author)
    created_at = DateTimeField(required=True)

    def __str__(self):
        return self.quote

quotes/forms.py
from django import forms

class AuthorForm(forms.Form):
    fullname = forms.CharField(max_length=50)
    born_date = forms.CharField(max_length=50)
    born_location = forms.CharField(max_length=150)
    description = forms.CharField(widget=forms.Textarea)

class QuoteForm(forms.Form):
    quote = forms.CharField(min_length=10, widget=forms.Textarea(attrs={'rows': 3}))

class TagForm(forms.Form):
    name = forms.CharField(min_length=3, max_length=25, required=True, widget=forms.TextInput())

quotes/views.py
# quotes/views.py
from bson import ObjectId
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from django.urls import reverse
from .utils import get_mongodb
from .forms import AuthorForm, QuoteForm, TagForm

db = get_mongodb()


def main(request, page=1):
    quotes = list(db.quotes.find())
    authors = list(db.authors.find())
    tags_pipeline = [
        {"$unwind": "$tags"},
        {"$group": {"_id": "$tags", "quote_count": {"$sum": 1}}},
        {"$sort": {"quote_count": -1}},
        {"$limit": 10},
        {"$project": {"id": "$_id", "quote_count": 1, "_id": 0}}
    ]
    top = list(db.quotes.aggregate(tags_pipeline))
    per_page = 10
    paginator = Paginator(quotes, per_page)
    quotes_on_page = paginator.page(page)
    for author in authors:
        author['id'] = str(author['_id'])
    for quote in quotes:
        quote['author'] = str(quote['author'])
    return render(request, 'quotes/index.html', context={'quotes': quotes_on_page, 'authors': authors,'top': top})

def add_author(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            db.authors.insert_one(form.cleaned_data)
            return redirect(reverse('quotes:root'))
    else:
        form = AuthorForm()
    return render(request, 'quotes/add_author.html', {'form': form})


def add_quote(request):
    authors = list(db.authors.find())
    if request.method == 'POST':
        form = QuoteForm(request.POST)
        if form.is_valid():
            author_name = request.POST.get('author')
            author = db.authors.find_one({"fullname": author_name})
            if not author:
                form.add_error('author', 'Selected author does not exist.')
            else:
                tags_input = request.POST.get('tags')
                tags = [tag.strip() for tag in tags_input.split(',') if tag.strip()]
                quote_data = form.cleaned_data
                quote_data['author'] = author['_id']
                quote_data['tags'] = tags
                db.quotes.insert_one(quote_data)
                return redirect(reverse('quotes:root'))
    else:
        form = QuoteForm()
    return render(request, 'quotes/add_quote.html', {'form': form, 'authors': authors})



def author_info(request, _id):
    author_id = ObjectId(_id)
    author = db.authors.find_one({"_id": author_id})
    return render(request, 'quotes/author_info.html', {'author': author})


def quotes_by_tag(request, tag_name, page=1):
    quotes = list(db.quotes.find({"tags": tag_name}))
    per_page = 10
    paginator = Paginator(quotes, per_page)
    quotes_on_page = paginator.page(page)
    return render(request, 'quotes/index.html', context={'quotes': quotes_on_page})

quotes/templates/quotes/add_author.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add Author</title>
</head>
<body>
{% extends "quotes/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quotes:add_author' %}">
    {% csrf_token %}
    <div class="mb-3">
        <label class="form-label" for="fullname">Fullname</label>
        <input class="form-control" id="fullname" name="fullname" placeholder="Enter fullname" type="text">
    </div>
    <div class="mb-3">
        <label class="form-label" for="born_date">Born date</label>
        <input class="form-control" id="born_date" name="born_date" placeholder="Enter born date" type="text">
    </div>
    <div class="mb-3">
        <label class="form-label" for="born_location">Born location</label>
        <input class="form-control" id="born_location" name="born_location" placeholder="Enter born location" type="text">
    </div>
    <div class="mb-3">
        <label class="form-label" for="description">Description</label>
        <textarea class="form-control" id="description" name="description" placeholder="Enter description"></textarea>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

    {% endblock %}
</body>
</html>

quotes/templates/quotes/add_quote.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add quote</title>
</head>
<body>
{% extends "quotes/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quotes:add_quote' %}">
    {% csrf_token %}
    <div class="mb-3">
        <label class="form-label" for="quotes">Quote</label>
        {{ form.quote }}
    </div>
    <div class="mb-3">
        <label class="form-label" for="authors">Author</label>
        <select name="author" class="form-select">
            {% for author in authors %}
                <option value="{{ author.fullname }}">{{ author.fullname }}</option>
            {% endfor %}
        </select>
    </div>
   <div class="mb-3">
        <label class="form-label" for="tags">Tags (comma separated)</label>
        <input type="text" name="tags" class="form-control">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

{% endblock %}
</body>
</html>

quotes/templates/quotes/author_info.html
{% extends 'quotes/base.html' %}
{% load static %}
{% block  content %}

<div class="row">
    <div class="col-md-8">
        <h2 class="text" itemprop="text">
            {{author.fullname}}
        </h2>
        <h3 class="text">
            {{author.born_date}}
        </h3>
        <h4 class="text">
            {{author.born_location}}
        </h4>
        <p class="text">
            {{author.description}}
        </p>
    </div>
    
    </div>
</div>

{% endblock %}

quotes/templates/quotes/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotes/style.css' %}">
    <title>Homework</title>
</head>
<body>
    <div class="container">
        <div class="row header-box pt-3">
            <div class="col-md-8">
                <h1>
                    <a href="/" style="text-decoration: none">Quotes to Scrape</a>
                </h1>
            </div>
        </div>
    <nav style="margin-bottom: 20px; border-bottom: 2px solid; padding-left: 30px">
    {% if user.is_authenticated %}
    <ul>
        <li><a class="btn btn-primary" href="{% url 'quotes:add_quote' %}">Add Quote</a></li>
        <li><a class="btn btn-primary" href="{% url 'quotes:add_author' %}">Add Author</a></li>
    </ul>
    <ul>
        <li>Welcome <b>{{ users.username }}!</b></li>
        <li><a href="{% url 'users:profile' %}" role="button">Profile</a></li>
        <li><a href="{% url 'users:logoutuser' %}" role="button">Logout</a></li>
    </ul>
    {% else %}
    <ul>
        <li><a href="{% url 'users:signup' %}" role="button">Sign Up</a></li>
        <li><a href="{% url 'users:signin' %}" role="button">Login</a></li>
    </ul>
    {% endif %}
</nav>
        {% block content %} {% endblock %}
    </div>
</body>
</html>

quotes/templates/quotes/index.html
{% extends 'quotes/base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <div class="row">
        <!-- Left block -->
        <div class="col-md-8">
            {% for quote in quotes %}
            <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
                <span class="text" itemprop="text">
                    {{quote.quote}}
                </span>
                {% for author in authors %}
                    {% if quote.author == author.id %}
                        <span>by <small class="author" itemprop="author">{{ author.fullname }}</small>
                            <a href="{% url 'quotes:author_info' author.id %}">(about)</a>
                        </span>
                    {% endif %}
                {% endfor %}
                <div class="tags">
                    Tags:
                    {% for tag in quote.tags %}
                     <a class="tag" href="{% url 'quotes:quotes_by_tag' tag %}">{{ tag }}</a>
                    {% endfor %}
                </div>
            </div>
            {% endfor %}

            <nav>
                <ul class="pager">
                    <li class="previous">
                        <a class='{% if not quotes.has_previous %} disabled {% endif %}'
                           href="{% if quotes.has_previous %} {% url 'quotes:root_paginate' quotes.previous_page_number %} {% else %} # {% endif %}">
                            <span aria-hidden="true">←</span> Previous
                        </a>
                    </li>
                    <li class="next">
                        <a class='{% if not quotes.has_next %} disabled {% endif %}'
                           href="{% if quotes.has_next %} {% url 'quotes:root_paginate' quotes.next_page_number %} {% else %} # {% endif %}">
                            Next <span aria-hidden="true">→</span>
                        </a>
                    </li>
                </ul>
            </nav>
        </div>

        <!-- Right block -->
        <div class="col-md-4">
            {% if top %}
            <div class="top">
                <h2>Top Tags:</h2>
                {% for tag in top %}
                <a class="tag" href="/tag/{{tag.id}}">{{tag.id}}</a>
                {% endfor %}
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}